# .bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return
PS1='[\u@\h \W]\$ '
alias ping='ping voidlinux.org'
alias remove='sudo xbps-remove -v'
alias yeet='sudo xbps-remove -Rov'
alias remorphan='sudo xbps-remove -ov'
alias remcache='sudo xbps-remove -Ov'
alias install='sudo xbps-install -v'
alias gimme='sudo xbps-install -Sv'
alias reinstall='sudo xbps-install -Sfv'
alias update='sudo xbps-install -Suv'
alias reconf='sudo xbps-reconfigure -fv'
alias show='sudo xbps-query'
alias search='sudo xbps-query -Rs'
#alias showall='sudo xbps-query -l | awk "{ print $2 }" | xargs -0 -n1 xbps-uhelper getpkgname'
alias showman='sudo xbps-query -m | awk "{ print $2 }" | xargs -n1 xbps-uhelper getpkgname'
alias showdeps='sudo xbps-query -x'
alias gitpull='git pull --autostash --rebase'
alias src='./xbps-src pkg'
alias src-update='./xbps-src show-sys-updates'
alias up='cd ..'
alias shutdown='loginctl poweroff'
alias poweroff='loginctl poweroff'
alias reboot='loginctl reboot'
alias n='nnn -Hod'
alias cl='clear'
alias svim='sudo vim'
alias zzz='sudo zzz'
alias xx='startx'
alias logs='sudo svlogtail'
alias spt='spotifyd && spotify-tui'
alias updatedb='sudo updatedb'
alias wttr='curl wttr.in'
alias btt='bluetoothctl'
alias ll='ls --color=auto -la'
alias ht='htop'
alias bat='acpi -V'
